### ISSUE TITLE
请问是不是支持url设置connectTimeout等类似超时参数 [QUESTION]

### ISSUE THREAD

**Issue by zonas0574** [aliyun/aliyun-odps-jdbc#104]
我看文档没说有类似超时设置
类似mysql jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&connectTimeout=60000&socketTimeout=60000

**Comment by cornmonster** [comment]
目前不支持，默认值为：
1. 建立连接超时时间为 10s
2. 读超时120s
