### ISSUE TITLE
[BUG]Cannot get corrent resultSetMetaData when disable useInstanceTunnel

### ISSUE THREAD

**Issue by njujianglan** [aliyun/aliyun-odps-jdbc#114]
**Describe the bug**
开启interactiveMode 关闭useInstanceTunnel时，resultSetMetaData中的columnType全部变成了String，丢失了正确的类型

**To Reproduce**
SQL: select count(a), x from (select 1.0 as a,1 as x) as y group by x
期望的结果是：BIGINT, BIGINT
目前返回结果：STRING, STRING

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cornmonster** [comment]
不走instance tunnel时获取结果仅支持用于屏幕显示，不支持进行进一步运算，因此schema均为String

这个issue后续我们会进行优化
