### ISSUE TITLE
[BUG] Spark JDBC connection using ODPS JDBC driver is returning column name as values.

### ISSUE THREAD

**Issue by gopesh1992** [aliyun/aliyun-odps-jdbc#126]
**Describe the bug**
Spark JDBC connection using ODPS JDBC driver is returning column name as values instead of actual values from source table.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Java version => openjdk version "11.0.11"
2. Your MaxCompute JDBC Driver version =>  3.2.9
3. Full stack of the error. => No error in connectivity, just that it returns rows same as column value
4. Minimized code to reproduce the error.
spark_df=spark.read.format("jdbc")\
        .option("url", "jdbc:odps:ENDPOINT?project=PROJECT_NAME&charset=UTF-8")\
        .option("query", "select * from sample")\
        .option("driver", "com.aliyun.odps.jdbc.OdpsDriver")\
        .option("queryTimeout", "3600")\
        .load()

spark_df.show() =>
col1 | col2
----------
col1 | col2
col1 | col2
col1 | col2

**Expected behavior**
Dataframe spark_df should hold all the columns and its respective and its values from the source table and it should not return column name as value. 
**Screenshots**

**Additional context**

**Comment by joerg-schneider** [comment]
The underlying mechanics seems to be the following:
1. Spark JDBC quoting field names for safety using double-quote, e.g. `21/09/29 21:21:20 INFO 2: create prepared statements: SELECT "column1","column2","column3","column4" FROM (select * from schema.table) SPARK_GEN_SUBQ_0 `
2. However, Maxcompute interpreting tokens sourrounded by double-quotes (`"`) not as quoted identifiers, but rather as strings: `In MaxCompute SQL, you can represent a string constant by using single quotation marks or double quotation marks.` (from the reference)

Point two is seems unusual and rare from a database perspective, which likely is the reason this bug has not been anticipated by the Spark developers. Also the SQL 1992 standard (https://datacadamia.com/_media/data/type/relation/sql/sql1992.txt) defines: `<delimited identifier> ::=
              <double quote> <delimited identifier body> <double quote>`

I see two possibilities to make Spark JDBC work with this driver:
- replace double quote (`"`) with backtick (`) from the raw SQL being passed-in to make queries sent to MaxCompute follow its unusual syntax. This could be switched off by default, but activated based on a JDBC property if needed
- (if exists?) control quoting syntax behaviour on the MaxCompute side as a database session property – so far I did not find this

Any feedback from the maintainers is appreciated, thanks.

**Comment by lyman** [comment]
@joerg-schneider is right. MaxCompute SQL treats double-quotes as string, and an identifier should be quoted with back quotation mark.

1.  It seems Spark JDBC ignored DatabaseMetaData.getIdentifierQuoteString implemtated in our JDBC driver.
2. There's no way to control quoting syntax on MaxCompute server side.
3. To use MaxCompute as a data source in Spark, the JDBC way has not been validated so far: a) draging massive data through single JDBC connection will be too slow, b) MaxCompute SQL does not support paging syntax like limit/offset so it could be tricky if Spark JDBC has a distributed implementation.
4. We are very close to publish MaxCompute official Spark connector. Maybe a week or two if everything goes fine.

**Comment by lyman** [comment]
Official spark datasource for MaxCompute is available now: 
https://github.com/aliyun/aliyun-maxcompute-data-collectors/blob/master/spark-datasource-v2.3/README-en.md
https://github.com/aliyun/aliyun-maxcompute-data-collectors/blob/master/spark-datasource-v3.1/README-en.md

**Comment by yingce** [comment]
@lyman
Thanks, works on spark version 2.3.x
Are there plans to support version 2.4 version
