### ISSUE TITLE
[QUESTION] 分区表怎么批量插入

### ISSUE THREAD

**Issue by guandatawangjialin** [aliyun/aliyun-odps-jdbc#137]
insert into table jialin_test partition(type) (title, name, type) values('2', 'jialin', 'hangzhou');
调用executeBatch方法提示sql不正确
使用正确sql语法又不能指定分区 求解

**Comment by cornmonster** [comment]
JDBC 目前不支持批量插入分区表，建议采用 MaxCompute SDK：https://help.aliyun.com/document_detail/27843.html
