### ISSUE TITLE
[QUESTION]超时时间设置

### ISSUE THREAD

**Issue by dufuqiubai** [aliyun/aliyun-odps-jdbc#139]
可以设置超时时间吗？

**Comment by yefanjiang** [comment]
> 可以设置超时时间吗？
可以的。OdpsConnection类里透出了readTimeout和connectTimeout。
connectTimeout 默认10s,  readTimeout 默认120s, 即总的超时连接时间是130s，默认重试次数是3次。
建议：想要调节超时时间，修改readTimeout即可，于是总的时间是 readTimeout+10s

**Comment by yefanjiang** [comment]
升级到最新版即可使用
