### ISSUE TITLE
getTables() is slow

### ISSUE THREAD

**Issue by onesuper** [aliyun/aliyun-odps-jdbc#14]
It took JDBC to read 330 tables's meta! A GUI user can not that longer

```
35e9e53527e8 [FINE] It took me 43669 ms to get 330 Tables
```

**Comment by BillLucky** [comment]
Do you have access to table names and other additional information?
If you just get the table name is very fast, other attributes such as: comments, owner, size, life cycle values are requested by lazy loading, each attribute corresponds to a request, so it will be very slow.

Just get the table name faster, hope to be useful to you.

**Comment by lyman** [comment]
`Tables.loadTables()` might worth a try

**Comment by lyman** [comment]
`Tables.loadTables()` already applied with https://github.com/aliyun/aliyun-odps-jdbc/pull/64
