### ISSUE TITLE
[BUG] logging in flawed path

### ISSUE THREAD

**Issue by arjenzhou** [aliyun/aliyun-odps-jdbc#140]
https://github.com/aliyun/aliyun-odps-jdbc/blob/8526844dd477b985c55956b07eea597f4a4b539a/src/main/java/com/aliyun/odps/jdbc/utils/OdpsLogger.java#L127-L136

From these lines of code, `odps-jdbc` will log a `jdbc.log` file in `BOOT-INF/lib` where should library jar files exsit only.

**Comment by yefanjiang** [comment]
hi, we have fixed this bug, you can use jdbc v3.3.4 as follows:
● By default, enableOdpsLogger=false, jdbc will not print the log to the file.
● When enableOdpsLogger=true is set, the log will be printed to the jdbc.log file in the same directory as the jdbc jar
● Through logConfFile, the log output can be flexibly configured by additionally specifying the slf4j configuration file (such as specifying the output file, output level, etc.) This method requires adding dependencies to the project's pom file:
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-core</artifactId>
  <version>1.2.3</version>
</dependency>
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-classic</artifactId>
  <version>1.2.3</version>
</dependency>
and slf4j configuration file: https://github.com/aliyun/aliyun-odps-jdbc/blob/master/logback/logback.xml
