### ISSUE TITLE
[FEATURE] ODPS的JDBC driver应该能够识别到priority的set，然后传递给ODPS客户端 

### ISSUE THREAD

**Issue by luxward** [aliyun/aliyun-odps-jdbc#146]
需求：希望能在SQL中或者其他地方set优先级并进行调度。

**Comment by yefanjiang** [comment]
https://help.aliyun.com/document_detail/175617.html?spm=a2c4g.34614.0.0.2d5d7040FnmfGB
想要使用这样的功能，必须在项目级别或者quota级别开启功能。此外，要求必须是包年包月的quota。
使用时，“set odps.instance.priority=values; your_sql”，set命令和sql命令之间用分号隔开，即可规定优先级。
