### ISSUE TITLE
PreparedStatement批量执行时，预执行sql中分区字段的值能否使用占位符？

### ISSUE THREAD

**Issue by W1433277729** [aliyun/aliyun-odps-jdbc#148]
通过代码中的正则表达式来看，现在是不支持的，只能写死分区的值，能否可以使用占位符
例如：INSERT INTO tablename partition(ptColumn1=?, ptColumn2=?) VALUES (?, ?, ?)

executeBatch()方法
![image](https://github.com/aliyun/aliyun-odps-jdbc/assets/57581067/6d0dce7e-8496-4e81-8d18-04e48604fd8a)

正则表达式
![image](https://github.com/aliyun/aliyun-odps-jdbc/assets/57581067/542e27c3-5c12-4edf-af2e-f57fb35cecc9)

**Comment by W1433277729** [comment]
看代码，底层调用的还是SDK，也是只能写死分区吗

**Comment by yefanjiang** [comment]
是的 只能写死分区。不支持占位符
