### ISSUE TITLE
[QUESTION] ODPS的JDBC接口有限制么？比如我通过python的JayDeBeApi可以访问ODPS吗？

### ISSUE THREAD

**Issue by Eiji911** [aliyun/aliyun-odps-jdbc#149]
A clear and concise description of what the problem is.
以及在性能上和使用pythonSDK对比有损失吗？

**Comment by yefanjiang** [comment]
ODPS的JDBC本质上是对ODPS Java SDK的封装。使用的接口限制可以参考aliyun官网https://help.aliyun.com/zh/maxcompute/user-guide/jdbc-reference/?spm=a2c4g.11186623.0.0.409c7268113jdf

**Comment by yefanjiang** [comment]
应该可以通过python的JayDeBeApi进行访问，可以试一下。我理解本质上没区别。
性能上和使用pythonSDK对比有损失吗？指的是JayDeBeApi和直接用python SDK吗？没进行过这样的对比，不太能给出结论。

**Comment by Eiji911** [comment]
> ODPS的JDBC本质上是对ODPS Java SDK的封装。使用的接口限制可以参考aliyun官网https://help.aliyun.com/zh/maxcompute/user-guide/jdbc-reference/?spm=a2c4g.11186623.0.0.409c7268113jdf

对于非阿里云部署的ODPS，也可以访问吗？

**Comment by yefanjiang** [comment]
什么叫非阿里云部署的ODPS？
