### ISSUE TITLE
Support implicit type conversion when setting upload field

### ISSUE THREAD

**Issue by onesuper** [aliyun/aliyun-odps-jdbc#17]
If a user wants to set up a field of Datatime by feeding a string, we should allow it any way.

For example:

```
prep_sql = "insert into table values(?)"
prep_statement.setString("timesamp", "2015-1-1 10:23:24") // timestamp is a Datetime in ODPS table
prep_statement.addBatch
```

However the current code base will say: java.lang.ClassCastException: [B cannot be cast to java.util.Date

It is a feature with a low priority since he still can convert the string into ODPS-flavored datetime in his own code.

The logic may fall back to the skeleton in https://github.com/aliyun/aliyun-odps-jdbc/commit/6a3b0bdee199879c01131f9ce3c9f6ef94ce592b
  and coming up with the check and conversion part.

cc @lyman

**Comment by cornmonster** [comment]
Done
