### ISSUE TITLE
odps-jdbc提示成功，但实际检测不成功

### ISSUE THREAD

**Issue by lbb123456** [aliyun/aliyun-odps-jdbc#29]
https://yq.aliyun.com/articles/5588 我用odps-jdbc，使用里面的“批量数据导入”示例代码，导入到我的maxCompute，　odps-jdbc提示"b834f0552424 [INFO] It took me 72 ms to insert 1 records [0], 0.00 MiB/s" 显然导入是成功的样子，
为什么在我的maxCompute控制台上执行select * from table_name;查不到数据

**Comment by lyman** [comment]
你的代码，用的 jdbc 版本贴出来

**Comment by lbb123456** [comment]
抱歉，我没有调用close()方法，所以没有成功，我看批量插入的时候，没有放出插入分区的接口，我现在想把你们的开源项目下下来，重新改一下。支持分区批量插入

**Comment by emerson-zhao** [comment]
欢迎完成该功能并向我们贡献代码，希望能带上TestCase，之前已经有一个该需求的issue，这个可以关了https://github.com/aliyun/aliyun-odps-jdbc/issues/18
