### ISSUE TITLE
odps-jdbc 的url为什么不能用内网的地址

### ISSUE THREAD

**Issue by tianzhuo662** [aliyun/aliyun-odps-jdbc#30]

**Comment by emerson-zhao** [comment]
你是指endpoint吗？能将你的问题描述的具体点吗？ @tianzhuo662

**Comment by tianzhuo662** [comment]
DriverManager.getConnection("jdbc:odps:https://service.odps.aliyun.com/api"

java中，获取链接用的url：https://service.odps.aliyun.com/api是odps的公网地址吧？
内网地址是"http://odps-ext.aliyun-inc.com/api"，使用这个就无法获取链接

**Comment by emerson-zhao** [comment]
@tianzhuo662 这不是jdbc的问题，是你所处网段的问题，你看下这几个域名的差别，其中经典网络和VPC指的都是在ECS里的网络类型 https://help.aliyun.com/document_detail/34951.html 如果你指的内网是指公司办公网的话，请使用http://service-corp.odps.aliyun-inc.com/api

**Comment by tianzhuo662** [comment]
感谢您的邮件与解释，
但是我还是没太明白，我指的内网就是odps在ECS上的经典网络，因为odps经典网络效率较高而且在tunnel download过程是不收费的，而公网效率差，而且收费
所以，jdbc的链接只能使用 jdbc:odps:https://service.odps.aliyun.com/api，那么我在使用的时候应该使用的是odps的公网链接吧，我想用odps的经典网络就不行，还是说内部Endpoint会自动指向？？




田卓 Frank

北京掌慧纵盈科技股份有限公司
OpSmart Technology Co.,LTD.
地址：北京市朝阳区霄云路26号鹏润大厦B座1901
电话：010-52823681
网址：www.opsmarttech.com

 
发件人： Emerson
发送时间： 2017-03-03 20:10
收件人： aliyun/aliyun-odps-jdbc
抄送： tianzhuo662; Mention
主题： Re: [aliyun/aliyun-odps-jdbc] odps-jdbc 的url为什么不能用内网的地址 (#30)
@tianzhuo662 这不是jdbc的问题，是你所处网段的问题，你看下这几个域名的差别，其中经典网络和VPC指的都是在ECS里的网络类型 https://help.aliyun.com/document_detail/34951.html 如果你指的内网是指公司办公网的话，请使用http://service-corp.odps.aliyun-inc.com/api

**Comment by emerson-zhao** [comment]
@tianzhuo662 你上面的电话一直打不通，如果方便的话请钉钉或旺旺上加一下 楚项 ，方便即时沟通。我想了解下你说的“我想用odps的经典网络就不行”具体是如何的不行，看看如何帮你快速解决这个问题

**Comment by emerson-zhao** [comment]
该问题最终确认是odps-ext.aliyun-inc.com/api这个endpoint目前不支持https, 后续会跟进兼容这个事情
