### ISSUE TITLE
每次向表中插入一条数据，就会多出来一张表是什么原因？

### ISSUE THREAD

**Issue by whwspeed** [aliyun/aliyun-odps-jdbc#41]
![image](https://user-images.githubusercontent.com/37356747/52690415-9736db80-2f98-11e9-9a9d-af272729f6a9.png)

**Comment by whwspeed** [comment]
表名是jdbc_test，插入了两条记录，多出来上面两个表

**Comment by lyman** [comment]
简单的说，jdbc 目前被设计用来主要做数据查询方向的操作。目前使用 jdbc 做插入数据动作仅支持 PreparedStatement 一种，而且不支持分区表。

看你的截图，应该还是 1.x 的版本，这个系列每个查询都会被改写成 `create table as ...`，所以每个查询都会产生临时表。1.x 的时候可能连上述的插入支持也还没有。，只能做 select。
