### ISSUE TITLE
Optimize the `select * from table' query.

### ISSUE THREAD

**Issue by onesuper** [aliyun/aliyun-odps-jdbc#5]
In this case, we do not have to create a temp table as the result of the query, but shortcut to download the target table.

Since this query is very common.

**Comment by onesuper** [comment]
ping @lyman

**Comment by lyman** [comment]
Yeah, good point.

The difficult thing is how to judge the query is a simple select * from a single table. Merely judge query starts with "select *" is not accurate, we have to make sure there's only one table in from clause.

**Comment by onesuper** [comment]
How about this one?

```
sql.toLowerCase().matches(^\s+select\s+\*\s+from\s+\w+\s+$)
```

This one is strict enough to exclude the wrong case. Though it will fail to capture the case like:

```
select * from abc --comment
```

Since this optimization is a bonus. The ignorance is not harmful.

**Comment by lyman** [comment]
This should be better `^\s*select\s+\*from\s+(\w+\.)?\w+\s*$`:
- make leading and trailing space optional
- compatible with `select * from prj.table`

**Comment by onesuper** [comment]
Exactly

**Comment by onesuper** [comment]
No longer needed if instance tunnel is used.
