### ISSUE TITLE
ODPS支持CASE WHEN，但是执行SQL报错：

### ISSUE THREAD

**Issue by Malaban** [aliyun/aliyun-odps-jdbc#60]
![image](https://user-images.githubusercontent.com/30622529/66698201-716ffb00-ed0e-11e9-8dd1-49255a9f5577.png)
这段SQL放到我们的数据工厂执行时OK的，但是用程序调用时就报错：
```
SELECT t11.age_sec
        ,t11.n
        ,t2.s
        ,CONCAT(ROUND(t11.n / t2.s * 100 ,2) ,'%') AS age_ratio
        FROM (
        SELECT (CASE WHEN  age&gt;18 and age&lt;25 then '18-25岁'
        WHEN  age&gt;26 and age&lt;30 then '26-30岁'
        WHEN  age&gt;31 and age&lt;35 then '31-35岁'
        WHEN  age&gt;36 and age&lt;40 then '36-40岁'
        WHEN  age&gt;41 and age&lt;45 then '41-45岁'
        WHEN  age&gt;46 and age&lt;50 then '46-50岁'
        WHEN  age&gt;51 and age&lt;55 then '51-55岁'
        WHEN  age&gt;56 and age&lt;60 then '56-60岁'
        WHEN  age&gt;61  then '60岁以上'
         end) as age_sec
        ,COUNT(DISTINCT t1.uuid) AS n ,1 as id   from (
        select  uuid,birthday,datediff(getdate(),to_date(birthday,'yyyy-mm-dd'),'yyyy') as age
        from  cust_tag_all_zzzx a
        where 1=1 and birthday != '未知'
        <if test="sex != null and sex != ''"> and sex = #{sex} </if>
        <if test="age != null and age != ''"> and birthday &gt; ${age} </if>
        <if test="city != null and city != ''"> and city = #{city} </if>
        <if test="province != null and province != ''"> and province = #{province} </if>
        <if test="list != null and list.size > 0">
            <foreach collection="list" item="item" index="index">
                ${item.rel}
                ${item.tagId}
                ${item.value}
                <choose>
                    <when test="item.value == 'and birthday &gt;='">
                        ${item.val}
                    </when>
                    <otherwise>
                        #{item.val}
                    </otherwise>
                </choose>
            </foreach>
        </if>
        )t1
        group by (CASE WHEN  age&gt;18 and age&lt;25 then '18-25岁'
        WHEN  age&gt;26 and age&lt;30 then '26-30岁'
        WHEN  age&gt;31 and age&lt;35 then '31-35岁'
        WHEN  age&gt;36 and age&lt;40 then '36-40岁'
        WHEN  age&gt;41 and age&lt;45 then '41-45岁'
        WHEN  age&gt;46 and age&lt;50 then '46-50岁'
        WHEN  age&gt;51 and age&lt;55 then '51-55岁'
        WHEN  age&gt;56 and age&lt;60 then '56-60岁'
        WHEN  age&gt;61  then '60岁以上'
         end)
        )t11
        JOIN (SELECT COUNT(DISTINCT a.uuid) AS s ,1 as id
        FROM cust_tag_all_zzzx a
        where 1=1 and birthday != '未知'
        <if test="sex != null and sex != ''"> and sex = #{sex} </if>
        <if test="age != null and age != ''"> and birthday &gt;= ${age} </if>
        <if test="city != null and city != ''"> and city = #{city} </if>
        <if test="province != null and province != ''"> and province = #{province} </if>
        <if test="list != null and list.size > 0">
            <foreach collection="list" item="item" index="index">
                ${item.rel}
                ${item.tagId}
                ${item.value}
                <choose>
                    <when test="item.value == 'and birthday &gt;='">
                        ${item.val}
                    </when>
                    <otherwise>
                        #{item.val}
                    </otherwise>
                </choose>
            </foreach>
        </if>
        )t2
        ON t11.id = t2.id ;
```

**Comment by lyman** [comment]
跟 case when 没关系。query 里这堆 <if> 之类的标签是干嘛的，这肯定不支持

**Comment by Malaban** [comment]
那是mybatis的动态标签。打印出来的SQL是这样：您看看有没有问题
`SELECT t11.age_sec
     , t11.n
     , t2.s
     , CONCAT(ROUND(t11.n / t2.s * 100, 2), '%') AS age_ratio
FROM (
         SELECT (CASE
                     WHEN (age >= 18 and age <= 25) then '18-25岁'
                     WHEN (age >= 26 and age <= 30) then '26-30岁'
                     WHEN (age >= 31 and age <= 35) then '31-35岁'
                     WHEN (age >= 36 and age <= 40) then '36-40岁'
                     WHEN (age >= 41 and age <= 45) then '41-45岁'
                     WHEN (age >= 46 and age <= 50) then '46-50岁'
                     WHEN (age >= 51 and age <= 55) then '51-55岁'
                     WHEN (age >= 56 and age <= 60) then '56-60岁'
                     WHEN age >= 61 then '60岁以上'
                     else '其他' end)     as age_sec
              , COUNT(DISTINCT t1.uuid) AS n
              , 1                       as id
         from (
                  select uuid, birthday, datediff(getdate(), to_date(birthday, 'yyyy-mm-dd'), 'yyyy') as age
                  from cust_tag_all_zzzx a
                  where 1 = 1
                    and birthday != '未知'
              ) t1
         group by (CASE
                       WHEN (age >= 18 and age <= 25) then '18-25岁'
                       WHEN (age >= 26 and age <= 30) then '26-30岁'
                       WHEN (age >= 31 and age <= 35) then '31-35岁'
                       WHEN (age >= 36 and age <= 40) then '36-40岁'
                       WHEN (age >= 41 and age <= 45) then '41-45岁'
                       WHEN (age >= 46 and age <= 50) then '46-50岁'
                       WHEN (age >= 51 and age <= 55) then '51-55岁'
                       WHEN (age >= 56 and age <= 60) then '56-60岁'
                       WHEN age >= 61 then '60岁以上'
                       else '其他' end)
     ) t11
         JOIN (SELECT COUNT(DISTINCT a.uuid) AS s, 1 as id
               FROM cust_tag_all_zzzx a
               where 1 = 1
                 and birthday != '未知'
) t2
              ON t11.id = t2.id;`

这段sql程序执行就报错，instanceId都没有生成。但是放到平台执行就ok。

**Comment by lyman** [comment]
jdbc jar 所在目录应该有个 jdbc.log 文件，发出来看看里面报什么错
