### ISSUE TITLE
[FEATURE] Support Tableau user defined SQL feature 

### ISSUE THREAD

**Issue by cornmonster** [aliyun/aliyun-odps-jdbc#72]
**Is your feature request related to a problem? Please describe.**
Tableau has a feature called user defined SQL. It will call the following unsupported method: com.aliyun.odps.jdbc.OdpsPreparedStatement.getMetaData 

Currently user could use MaxCompute view to work around. But supporting this method could still be an improvement of user experience.

**Describe the solution you'd like**
A long term solution should be using an embedded  SQL compiler to get the result set metadata. 

A short term way could be executing the query and cache the result when calling getMetaData. Then the followed execute() could be skipped and the result set could be returned immediately.

**Comment by momo9** [comment]
And I think odps-jdbc will not return partition columns when some methods are called to get meta-data (by Tableau) such as columns.

When I using Tableau to connect ODPS, I found the partition columns were not imported. Then I tried to use "user defined SQL" and just encountered the problem described in this issue.

**Comment by cornmonster** [comment]
> And I think odps-jdbc will not return partition columns when some methods are called to get meta-data (by Tableau) such as columns.
> 
> When I using Tableau to connect ODPS, I found the partition columns were not imported. Then I tried to use "user defined SQL" and just encountered the problem described in this issue.

Make sense, will fix it.
