### ISSUE TITLE
连接tableau存在中文显示错误

### ISSUE THREAD

**Issue by Zpx007** [aliyun/aliyun-odps-jdbc#75]
通过tableau提供的alibaba maxcompute通道连接数据库存在中文显示错误。在进行表格计算时会将中文展示为类似quoted-printable形式的编码。如图：
<img width="401" alt="C0BC4E78-AACB-4e2a-A6C0-1B4AD2CEBEB0" src="https://user-images.githubusercontent.com/28784845/72055744-565d5900-3306-11ea-8378-8d07bf7d7abc.png">
通过tableau提供的postgresql通道连接odps则不存在该问题，tableau官方认为可能是jdbc的问题。
JDBC和tableau都是最新版本。

**Comment by lyman** [comment]
请提供一下复现步骤
