### ISSUE TITLE
show tables；求解答！

### ISSUE THREAD

**Issue by YeHangTheDew** [aliyun/aliyun-odps-jdbc#77]
使用这个项目对odps进行了show tables;操作，出现了个不存在文档里的错误码。
测试其他查询语句，正常，求大佬解答下
![image](https://user-images.githubusercontent.com/35034994/76945994-51d4a280-693e-11ea-848e-cf12adb694f5.png)
![image](https://user-images.githubusercontent.com/35034994/76946094-7466bb80-693e-11ea-90f3-f31a41c4ad3d.png)

**Comment by cornmonster** [comment]
对DDL拿ResultSet了吧

**Comment by lyman** [comment]
show tables 因为历史原因还能被 sql 解析，但是是不返回 ResultSet 的

jdbc 里面正确获取 table 元数据的方式是 DatabaseMetaData.getTables()
