### ISSUE TITLE
[QUESTION]怎么获取分区表的分区字段及属性

### ISSUE THREAD

**Issue by zhengguilin** [aliyun/aliyun-odps-jdbc#78]
A clear and concise description of what the problem is.

**Comment by cornmonster** [comment]
```
Connection conn = getConnection();
OdpsMetaData metadata = (OdpsMetaData) conn.getMetaData();
ResultSet rs = metadata.getColumns();
```

See https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)
