### ISSUE TITLE
[BUG]日志重复打印，每创建一次连接多打印一次日志

### ISSUE THREAD

**Issue by sanluan** [aliyun/aliyun-odps-jdbc#84]
**Describe the bug**
日志重复打印，每创建一次连接多打印一次日志
OdpsDriver. connect(url, info);方法中调用new OdpsConnection(url, info) ；
每次都会实例化一个log
    log = new OdpsLogger(getClass().getName(), null, logConfFile, false, connRes.isEnableOdpsLogger());
在OdpsLogger中
odpsLogger= Logger.getLogger(name);
每次实例会追加一个fileHanlder到odpsLogger;  
odpsLogger.addHandler(fileHandler);
导致创建一万次连接后，一条日志会在jdbc.log中打印一万遍

**Comment by lyman** [comment]
收到，下个版本 fix

https://developer.aliyun.com/ask/310170

**Comment by sanluan** [comment]
那个也是我提的哈 多个渠道反馈
