### ISSUE TITLE
怎么设置日志级别（spring + druid下）

### ISSUE THREAD

**Issue by weishengbin** [aliyun/aliyun-odps-jdbc#89]
A clear and concise description of what the problem is.

**Comment by cornmonster** [comment]
MaxCompute JDBC driver只引入了sl4j api，没有引入具体的binding。你可以自行选择log4j，logback或其他binding。

之后，在配置文件中配置好你需要的logging level，pattern等等信息，通过连接串中“logconffile”参数指定日志配置文件的位置，比如：
```
jdbc:odps:http://service.cn.maxcompute.aliyun.com/api?project=test&logconffile=/path/to/log4j.xml
```
