### ISSUE TITLE
[QUESTION]SQL Workbench/J  Access Error

### ISSUE THREAD

**Issue by Jenson-ZhangXu** [aliyun/aliyun-odps-jdbc#98]
A clear and concise description of what the problem is.
![image](https://user-images.githubusercontent.com/7358611/96536936-b3d7fa80-12c7-11eb-9052-8f76c258c902.png)

![image](https://user-images.githubusercontent.com/7358611/96537015-de29b800-12c7-11eb-92bd-222013520b9b.png)

**Comment by cornmonster** [comment]
There should be a log file named jdbc.log under D:/dev/driver/. Could you upload it?

**Comment by Jenson-ZhangXu** [comment]
我没有在 D:/dev/driver/  发现log文件。
我使用lightning.ap-southeast-1.maxcompute.aliyun.com完成了，对maxcompute的访问
谢谢!

Zhong Wang <notifications@github.com> 于2020年12月24日周四 上午11:07写道：
